services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.rule=Host(`nginx1.localhost`)"
      - "traefik.http.services.nginx1.loadbalancer.server.port=80"
