services:
  nginx:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=Host(`nginx2.localhost`)"
      - "traefik.http.services.nginx2.loadbalancer.server.port=80"
